// Hand-drawn 16x16 pixel art.  Each shape is 16 strings of 16 characters;
// '.' is transparent and every other character is looked up in a palette.
// Shared letters: k outline · w white · s skin · e eye · h hair
// Shape-specific letters (A main, B shade, C highlight, D accent, …) are
// swapped per palette so one shape yields several monsters.

const SHARED = { k: '#14121a', w: '#f4f1ea', s: '#f1c9a5', e: '#1a1a2e', h: '#5a3a1e', m: '#b5583a', g: '#8b8f99', y: '#f2c94c' };

export const SHAPES = {
  heroDown: [
    '....kkkkkk......',
    '...khhhhhhk.....',
    '..khhyyyyhhk....',
    '..khsssssshk....',
    '..kssesseesk....',
    '..kssssssssk....',
    '...kssmmssk.....',
    '....kkkkkk......',
    '...kCyyyyCk.....',
    '..kCAwAAwACk.tk.',
    '.ksCAAAAAACskwk.',
    '.kkBAAyAAABkkgk.',
    '..kBByyyyBBk.k..',
    '..kBBkkkkBBk....',
    '..kBB....BBk....',
    '..kkk....kkk....',
  ],
  heroUp: [
    '....kkkkkk......',
    '...khhhhhhk.....',
    '..khhhhhhhhk....',
    '..khhhhhhhhk....',
    '..khhhhhhhhk....',
    '..khhhhhhhhk....',
    '...khhhhhhk.....',
    '....kkkkkk......',
    '.tk.kCyyyyCk....',
    '.kwkkCAAAACk....',
    '.kgksCAAAACsk...',
    '..k.kCABBACBk...',
    '....kByyyyBk....',
    '....kBBkkBBk....',
    '....kBB..BBk....',
    '....kkk..kkk....',
  ],
  heroLeft: [
    '.....kkkkkk.....',
    '....khhhhhhk....',
    '...khhhhhhhhk...',
    '...khsssshhhk...',
    '...ksesssshhk...',
    '...kssssshhk....',
    '....kmssshk.....',
    '.....kkkkk......',
    '....kCyyyBk.....',
    '..tkkCAAAABk....',
    '..kwsCAAAABk....',
    '..kgkCAAAABk....',
    '...kkByyyyBk....',
    '....kBBBBBk.....',
    '....kBB.BBk.....',
    '....kkk.kkk.....',
  ],
  heroRight: [
    '.....kkkkkk.....',
    '....khhhhhhk....',
    '...khhhhhhhhk...',
    '...khhhsssshk...',
    '...khhsssesk....',
    '....khsssssk....',
    '.....khsssmk....',
    '......kkkkk.....',
    '.....kByyyCk....',
    '....kBAAAACkkt..',
    '....kBAAAACswk..',
    '....kBAAAACkgk..',
    '....kByyyyBkk...',
    '.....kBBBBBk....',
    '.....kBB.BBk....',
    '.....kkk.kkk....',
  ],
  slime: [
    '................',
    '................',
    '.....kkkkkk.....',
    '....kCCCCCCk....',
    '...kCwwAAAACk...',
    '..kCCwAAAAAAk...',
    '..kCAAAAAAAAAk..',
    '.kAAAweAAAweAAk.',
    '.kAAAAAAAAAAAAk.',
    '.kAAAAAkkAAAAAk.',
    '.kABAAAAAAAABAk.',
    '.kBBBAAAAAABBBk.',
    '..kBBBBBBBBBBk..',
    '...kBBBBBBBBk...',
    '....kkkkkkkk....',
    '................',
  ],
  slimeKing: [
    '....y..yy..y....',
    '....yyyyyyyy....',
    '....kyyyyyyk....',
    '...kCCCCCCCCk...',
    '..kCCAAAAAACCk..',
    '..kAAAAAAAAAAk..',
    '.kAAAeAAAAAeAAk.',
    '.kAAAAAAAAAAAAk.',
    '.kAAAAkkkkAAAAk.',
    '.kAAAAkwwkAAAAk.',
    '.kABAAAkkAAABAk.',
    '.kBBBAAAAAABBBk.',
    '..kBBBBBBBBBBk..',
    '...kBBBBBBBBk...',
    '....kkkkkkkk....',
    '................',
  ],
  bat: [
    '................',
    '................',
    '.k...........k..',
    '.kB.........Bk..',
    '.kBB..kkk..BBk..',
    '.kBBBkAAAkBBBk..',
    '.kBBBkeAekBBBk..',
    '..kBBkAAAkBBk...',
    '..kBBBAkABBBk...',
    '...kBBBAABBBk...',
    '....kBkAAkBk....',
    '.....k.kk.k.....',
    '......k..k......',
    '................',
    '................',
    '................',
  ],
  skeleton: [
    '.....kkkkkk.....',
    '....kwwwwwwk....',
    '...kwwwwwwwwk...',
    '...kwkkwwkkwk...',
    '...kwkkwwkkwk...',
    '...kwwwwwwwwk...',
    '....kwkwwkwk....',
    '.....kkkkkk.....',
    '..kk..kwwk..kk..',
    '.kwwkkkwwkkkwwk.',
    '.kwkkwwwwwwkkwk.',
    '..k.kwkwwkwk.k..',
    '....kwwwwwwk....',
    '.....kwkkwk.....',
    '....kwk..kwk....',
    '....kkk..kkk....',
  ],
  skeletonSoldier: [
    '....kkkkkkkk....',
    '...kAAAAAAAAk...',
    '...kAABAAABAk...',
    '...kwwwwwwwwk...',
    '...kwkkwwkkwk...',
    '...kwwwwwwwwk...',
    '....kwkwwkwk....',
    '..kk.kkkkkk.kk..',
    '.kDDkkAAAAkkgtk.',
    '.kDwDkAAAAkkgk..',
    '.kDDDkABBAk.gk..',
    '..kkkkAAAAk.k...',
    '.....kwwwwk.....',
    '.....kwkkwk.....',
    '....kwk..kwk....',
    '....kkk..kkk....',
  ],
  orc: [
    '....kkkkkkk.....',
    '...kAAAAAAAk....',
    '..kAAAAAAAAAk...',
    '..kAAeAAAeAAk...',
    '..kAAAAAAAAAk...',
    '..kAwAAAAAwAk...',
    '...kkAkkkAkk....',
    '....kkkkkkk.....',
    '..kBBkDDDDkBBk..',
    '.kAAkDDDDDDkAAk.',
    '.kAAkDDDDDDkAAk.',
    '..kkkDDDDDDkkk..',
    '....kDDDDDDk....',
    '....kBBkkBBk....',
    '....kBB..BBk....',
    '....kkk..kkk....',
  ],
  guard: [
    '.....kkkkkk.....',
    '....kAAAAAAk....',
    '...kAAAAAAAAk...',
    '...kAkkkkkkAk...',
    '...kAksseskAk...',
    '...kAksssskAk...',
    '....kkkkkkkk.k..',
    '.....kkkkkk.kgk.',
    '..kk.kAAAAk.kgk.',
    '.kDDkkABBAkkkgk.',
    '.kDwDkABBAk.kgk.',
    '.kDDDkAAAAk.kgk.',
    '..kkkkAAAAk.kgk.',
    '.....kBBBBk.k.k.',
    '....kBBkkBBk....',
    '....kkk..kkk....',
  ],
  knight: [
    '......Dkk.......',
    '.....DkAAk......',
    '....kkAAAAk.....',
    '...kAAAAAAAAk...',
    '...kAkkkkkkAk...',
    '...kAkeekeekAk..',
    '...kAAkkkkAAk...',
    '....kkkkkkkk....',
    '..kkkAAAAAAkkk..',
    '.kBBkAACCAAkBBk.',
    '.kBBkACAACAkBBk.',
    '..kkkAACCAAkkk..',
    '....kAAAAAAk....',
    '....kBBkkBBk....',
    '....kBB..BBk....',
    '....kkk..kkk....',
  ],
  mage: [
    '.......kk.......',
    '......kAAk......',
    '.....kAAAAk.....',
    '....kAAAAAAk....',
    '...kAAAAAAAAk...',
    '..kkkkkkkkkkkk..',
    '....kssssssk.k..',
    '....kseseesk.kD.',
    '.....kssssk.kDk.',
    '....kkkkkkkkkgk.',
    '...kAABAABAAkgk.',
    '..kAAABAABAAAgk.',
    '..kAAABAABAAkgk.',
    '..kAAAAAAAAAkgk.',
    '..kBBBBBBBBBk.k.',
    '...kkkkkkkkk....',
  ],
  rock: [
    '................',
    '.....kkkkkk.....',
    '...kkAAAAAAkk...',
    '..kAAAAAAAAAAk..',
    '.kAAAeAAAAeAAAk.',
    '.kAAAAAAAAAAAAk.',
    '.kAAAAAkkAAAAAk.',
    '.kBAAAkkkkAAABk.',
    'kAAkBBBBBBBBkAAk',
    'kAAkBBBBBBBBkAAk',
    'kBBkBBBBBBBBkBBk',
    '.kkkBBBBBBBBkkk.',
    '...kBBBBBBBBk...',
    '...kBBBkkBBBk...',
    '..kBBBBkkBBBBk..',
    '..kkkkkk.kkkkk..',
  ],
  king: [
    '...y.y.yy.y.y...',
    '...yyyyyyyyyy...',
    '...kAAAAAAAAk...',
    '..kAAAAAAAAAAk..',
    '..kAAkkkkkkAAk..',
    '..kAkeekkeekAk..',
    '..kAkkkkkkkkAk..',
    '.kAAAkkkkkkAAAk.',
    'kAAAkBBCCBBkAAAk',
    'kAAAkBCBBCBkAAAk',
    'kAAAkBBCCBBkAAAk',
    'kAAAkBBBBBBkAAAk',
    'kAAAkBBBBBBkAAAk',
    'kAAAkBBkkBBkAAAk',
    'kkkkkBB..BBkkkkk',
    '....kkk..kkk....',
  ],
  fairy: [
    '......kkkk......',
    '.....kAAAAk.....',
    '....kAAAAAAk....',
    '....kAsssAAk....',
    'kk..ksesesAk.kk.',
    'kCk.kssssAk.kCk.',
    'kCCkkkkkkkkkCCk.',
    'kCCCkDDDDDkCCCk.',
    '.kCCkDwDDDkCCk..',
    '.kCCkDDDDDkCCk..',
    '..kkkDDDDDkkk...',
    '....kDDDDDDk....',
    '...kDDDDDDDDk...',
    '...kDDDDDDDDk...',
    '....kkkkkkkk....',
    '................',
  ],
  thief: [
    '....kkkkkkk.....',
    '...kAAAAAAAk....',
    '..kAAAAAAAAAk...',
    '..kkkkkkkkkkk...',
    '..kBBeBBBeBBk...',
    '..kBBBBBBBBBk...',
    '...ksssssssk....',
    '....kkkkkkk.....',
    '..kkkDDDDDkkk...',
    '.kssDDDDDDDssk..',
    '.kkkDDyDDDDkkk..',
    '...kDDDDDDDk....',
    '...kDDDDDDDk....',
    '...kBBkkkBBk....',
    '...kBB...BBk....',
    '...kkk...kkk....',
  ],
  oldman: [
    '.....kkkkkk.....',
    '....kwwwwwwk....',
    '...kwwwwwwwwk...',
    '...kssssssssk...',
    '...ksesssesskk..',
    '...kssssssskDk..',
    '...kwwwwwwwkDk..',
    '....kwwwwwkkDk..',
    '..kkkAAAAAkkDk..',
    '.kssAAAAAAAsDk..',
    '.kkkAAAAAAAkDk..',
    '...kAAAAAAAkDk..',
    '...kAAAAAAAkDk..',
    '...kAAAAAAAk.k..',
    '...kBBBBBBBk....',
    '....kkkkkkk.....',
  ],
  merchant: [
    '.....kkkkkk.....',
    '....kBBBBBBk....',
    '...kBhhhhhhBk...',
    '...kkhhhhhhkk...',
    '....khssssshk...',
    '....ksesssesk...',
    '....kssssssk....',
    '.....kkkkkk.....',
    '..kkkAAAAAAkkk..',
    '.kyykAAwAAAkssk.',
    '.kyykAAAAAAkkk..',
    '.kyykAAAAAAk....',
    '..kkkAAAAAAk....',
    '....kAAAAAAk....',
    '....kBBBBBBk....',
    '.....kkkkkk.....',
  ],
  princess: [
    '....y..yy..y....',
    '....yyyyyyyy....',
    '...khhhhhhhhk...',
    '..khhssssssshk..',
    '..khsesssseshk..',
    '..khsssssssshk..',
    '..khhsssssshhk..',
    '..khhkkkkkkhhk..',
    '..kkkAAAAAAkkk..',
    '.kssAAwAAAAAssk.',
    '.kkkAAAAAAAAkkk.',
    '...kAAAAAAAAk...',
    '..kAAAAAAAAAAk..',
    '..kAAAAAAAAAAk..',
    '.kAAAAAAAAAAAAk.',
    '.kkkkkkkkkkkkkk.',
  ],
  shop: [
    '................',
    '......kkkk......',
    '.....kAAAAk.....',
    '....kAAeAeAk....',
    '....kAAAAAAk....',
    '.....kAAAAk.....',
    '....kkkkkkkk....',
    '...kBBBBBBBBk...',
    '..kBBBBCCBBBBk..',
    '..kBBBCCCCBBBk..',
    '..kBBBBCCBBBBk..',
    '..kBBBBBBBBBBk..',
    '.kkkkkkkkkkkkkk.',
    '.kDDDDDDDDDDDDk.',
    '.kDDDDDDDDDDDDk.',
    '.kkkkkkkkkkkkkk.',
  ],
  // ---------------------------------------------------------------- items --
  key: [
    '................',
    '................',
    '......kkkk......',
    '.....kAAAAk.....',
    '....kAkkkkAk....',
    '....kAk..kAk....',
    '....kAkkkkAk....',
    '.....kAAAAk.....',
    '......kAAk......',
    '......kAAk......',
    '......kAAkk.....',
    '......kAAAk.....',
    '......kAAkk.....',
    '......kAAAk.....',
    '......kkkk......',
    '................',
  ],
  gem: [
    '................',
    '................',
    '.....kkkkkk.....',
    '....kCCCCCCk....',
    '...kCCwCAAAAk...',
    '..kCCwCAAAAAAk..',
    '..kCCCAAAAAABk..',
    '..kCAAAAAAABBk..',
    '..kAAAAAAABBBk..',
    '...kAAAAABBBk...',
    '....kAAABBBk....',
    '.....kAABBk.....',
    '......kABk......',
    '.......kk.......',
    '................',
    '................',
  ],
  potion: [
    '................',
    '......kkkk......',
    '......kwwk......',
    '......kkkk......',
    '......kAAk......',
    '.....kkAAkk.....',
    '....kAAAAAAk....',
    '...kAAAAAAAAk...',
    '...kACAAAAAAk...',
    '...kACAAAAABk...',
    '...kAAAAAABBk...',
    '...kAAAAABBBk...',
    '....kAABBBBk....',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  feather: [
    '................',
    '..........kk....',
    '.........kCAk...',
    '........kCAAk...',
    '.......kCAAAk...',
    '......kCAAAk....',
    '.....kCAAABk....',
    '....kCAAABk.....',
    '....kAAABBk.....',
    '...kAAABBk......',
    '...kAABBk.......',
    '..kAABBk........',
    '..kBBBk.........',
    '.kBBk...........',
    '.kkk............',
    '................',
  ],
  cross: [
    '................',
    '......kkkk......',
    '.....kAAAAk.....',
    '.....kACCAk.....',
    '..kkkkACCAkkkk..',
    '.kAAAAACCAAAAAk.',
    '.kACCCCrrCCCCAk.',
    '.kACCCCrrCCCCAk.',
    '.kAAAAACCAAAAAk.',
    '..kkkkACCAkkkk..',
    '.....kACCAk.....',
    '.....kACCAk.....',
    '.....kACCAk.....',
    '.....kAAAAk.....',
    '......kkkk......',
    '................',
  ],
  holyWater: [
    '................',
    '.....kkkkkk.....',
    '.....kyyyyk.....',
    '......kAAk......',
    '......kAAk......',
    '.....kkAAkk.....',
    '....kAAAAAAk....',
    '...kAwAAAAAAk...',
    '...kAwAACCAAk...',
    '...kAAACCCCAk...',
    '...kAAACCCCAk...',
    '...kAAAACCAAk...',
    '....kAAAAAAk....',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  badge: [
    '................',
    '....kkkkkkkk....',
    '....kDDkkDDk....',
    '....kDDkkDDk....',
    '.....kkkkkk.....',
    '.....kAAAAk.....',
    '....kAACCAAk....',
    '...kAACCCCAAk...',
    '...kACCwwCCAk...',
    '...kACCwwCCAk...',
    '...kAACCCCAAk...',
    '....kAACCAAk....',
    '.....kAAAAk.....',
    '......kkkk......',
    '................',
    '................',
  ],
  compass: [
    '................',
    '.....kkkkkk.....',
    '...kkAAAAAAkk...',
    '..kAAAAwwAAAAk..',
    '.kAAAAAwwAAAAAk.',
    '.kAAAAAwCAAAAAk.',
    'kAwwAAwCCAAAwwAk',
    'kAwwAwCCCCAAwwAk',
    'kAAAAACCCCwAAAAk',
    'kAAAAACCCwAAAAAk',
    '.kAAAAACwAAAAAk.',
    '.kAAAAAwwAAAAAk.',
    '..kAAAAwwAAAAk..',
    '...kkAAAAAAkk...',
    '.....kkkkkk.....',
    '................',
  ],
  keyBox: [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '.kAAAAAAAAAAAAk.',
    '.kACCCCCCCCCCAk.',
    '.kkkkkkkkkkkkkk.',
    '.kBBBBBkkBBBBBk.',
    '.kBBBBkyykBBBBk.',
    '.kBBBBkyykBBBBk.',
    '.kBBBBBkkBBBBBk.',
    '.kBBBBBBBBBBBBk.',
    '.kBBBBBBBBBBBBk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
  ],
  hammer: [
    '................',
    '...kkkkkkkk.....',
    '..kAAAAAAAAk....',
    '..kACCCrCAAk....',
    '..kACCCCCAAk....',
    '..kAAAAAAAAk....',
    '..kBBBBBBBBk....',
    '...kkkkDDkkk....',
    '.......kDDk.....',
    '.......kDDk.....',
    '.......kDDk.....',
    '.......kDDk.....',
    '.......kDDk.....',
    '.......kDDk.....',
    '........kk......',
    '................',
  ],
  nugget: [
    '................',
    '................',
    '................',
    '.....kkkkkk.....',
    '....kCCCCAAk....',
    '...kCwwCAAAAk...',
    '..kCCwCAAAAAAk..',
    '..kCCCAAAAAABk..',
    '..kCAAAAAAABBk..',
    '..kAAAAAAABBBk..',
    '..kAAAAABBBBBk..',
    '...kAABBBBBBk...',
    '....kkkkkkkk....',
    '................',
    '................',
    '................',
  ],
  sword: [
    '..........kk....',
    '.........kCCk...',
    '........kCAAk...',
    '.......kCAAk....',
    '......kCAAk.....',
    '.....kCAAk......',
    '....kCAAk.......',
    '.k.kCAAk........',
    '.kkkAAk.........',
    '..kDDk..........',
    '.kDkDDk.........',
    'kDk.kkDk........',
    'kk...kDDk.......',
    '......kDDk......',
    '.......kk.......',
    '................',
  ],
  shield: [
    '................',
    '..kkkkkkkkkkkk..',
    '.kAAAAAAAAAAAAk.',
    '.kACCCCCCCCCCAk.',
    '.kACBBBBBBBBCAk.',
    '.kACBBBDDBBBCAk.',
    '.kACBBDDDDBBCAk.',
    '.kACBBDDDDBBCAk.',
    '..kACBBDDBBCAk..',
    '..kACBBBBBBCAk..',
    '...kACBBBBCAk...',
    '....kACBBCAk....',
    '.....kACCAk.....',
    '......kAAk......',
    '.......kk.......',
    '................',
  ],
  staff: [
    '......kkkk......',
    '.....kCCCCk.....',
    '....kCAAAACk....',
    '....kCAAAACk....',
    '.....kCAACk.....',
    '......kAAk......',
    '.....kDkkDk.....',
    '......kDDk......',
    '......kDDk......',
    '......kDDk......',
    '......kDDk......',
    '......kDDk......',
    '......kDDk......',
    '......kDDk......',
    '.......kk.......',
    '................',
  ],
};

// ------------------------------------------------------------- palettes ----
const P = (o) => ({ ...SHARED, ...o });

export const PALETTES = {
  hero: P({ A: '#427b9e', B: '#244353', C: '#83c4ce', y: '#dfb86b', t: '#e4d9b4', g: '#8babb5', h: '#634833' }),
  green: P({ A: '#4fbf4a', B: '#2d7d2b', C: '#a6eb8a', D: '#7a4d2a', y: '#f2c94c', e: '#0f1a12' }),
  red: P({ A: '#d9453d', B: '#8f1f1a', C: '#ff9a8c', D: '#3a1a1a', y: '#f2c94c', e: '#2a0a0a' }),
  cyan: P({ A: '#3fb7c7', B: '#1f6f7e', C: '#a9eef5', e: '#0b1c22' }),
  gray: P({ A: '#8e8ea6', B: '#4d4d68', e: '#ff4b4b' }),
  purple: P({ A: '#8b5bd6', B: '#4b2c86', e: '#ffd34b' }),
  bone: P({ A: '#9c8a6a', B: '#6b5a40', D: '#b8b4a8', g: '#c7c7c7', t: '#ececec' }),
  captain: P({ A: '#d9453d', B: '#8f1f1a', D: '#e0c15c', g: '#c7c7c7', t: '#ececec' }),
  dark: P({ A: '#4a3d7a', B: '#2a2050', C: '#8a7ac9', D: '#8b3a9a', g: '#a9a3c9', t: '#e8e0ff', e: '#ff4b4b', w: '#d9d3ff' }),
  darkTrue: P({ A: '#2b1f4f', B: '#150c30', C: '#c04bd6', y: '#f2c94c', e: '#ff2a2a', w: '#c4b2ff' }),
  phantom: P({ A: '#3d5a6b', B: '#1d2f3b', C: '#8fd3f4', y: '#b8d8e6', e: '#7cf5ff', w: '#dff6ff' }),
  blue: P({ A: '#3f6fd6', B: '#24448f', D: '#e0c15c', g: '#c7c7c7', e: '#101a33' }),
  brown: P({ A: '#8b6a3f', B: '#5a4226', D: '#d9a441', g: '#8b5a2a', e: '#1a1008' }),
  violet: P({ A: '#7a3fd6', B: '#4a2489', D: '#f2c94c', g: '#c9a6ff', e: '#f8f0ff' }),
  white: P({ A: '#ececf2', B: '#b9b9cc', C: '#fff', D: '#d94b4b', e: '#3a6ad6' }),
  gold: P({ A: '#e0b23c', B: '#a57a1a', C: '#fff0a6', D: '#d94b4b', e: '#3a2a08' }),
  goldCaptain: P({ A: '#f0c95a', B: '#b3861f', C: '#ffffff', D: '#3a3aff', e: '#ff3a3a' }),
  shadow: P({ A: '#2e2e3a', B: '#151520', C: '#6a6a8a', D: '#8a2be2', e: '#ff3a3a' }),
  stone: P({ A: '#a09a8a', B: '#6b6558', e: '#ffd34b' }),
  armored: P({ A: '#6fa63f', B: '#3f6a22', D: '#7d7d8f', e: '#ff3a3a' }),
  swordsman: P({ A: '#c9a24b', B: '#8a6a24', D: '#a0a0b0', g: '#e4e4ec', e: '#1a1008' }),
  ghost: P({ A: '#5d6b8a', B: '#33405a', D: '#8a4bd6', g: '#b8c4e0', e: '#7cf5ff', s: '#c9d3e6' }),
  // npcs
  fairy: P({ A: '#7ad3ff', C: '#d6f4ff', D: '#ff9ad5', w: '#ffffff', h: '#7ad3ff' }),
  thief: P({ A: '#3a3a4a', B: '#5a5a70', D: '#7a5a3a', y: '#f2c94c' }),
  oldman: P({ A: '#8a7a5a', B: '#5a4a30', D: '#a06a2a' }),
  merchant: P({ A: '#4b8ad6', B: '#c94b7a', y: '#e0b23c', h: '#3a2a1a' }),
  princess: P({ A: '#ff8ac4', B: '#c94b7a', y: '#f2c94c', h: '#f2d16b' }),
  shop: P({ A: '#e0b23c', B: '#7a5ad6', C: '#c9b6ff', D: '#4a3a7a', e: '#fff' }),
  // items
  yellowKey: P({ A: '#f2c94c' }),
  blueKey: P({ A: '#4b8ad6' }),
  redKey: P({ A: '#e04b4b' }),
  redGem: P({ A: '#e04b4b', B: '#8f1f1a', C: '#ff9a8c' }),
  blueGem: P({ A: '#3f6fd6', B: '#24448f', C: '#9ac0ff' }),
  redPotion: P({ A: '#e04b4b', B: '#8f1f1a', C: '#ff9a8c' }),
  bluePotion: P({ A: '#3f8fd6', B: '#24488f', C: '#9ad0ff' }),
  smallFeather: P({ A: '#8fd3f4', B: '#3f8fd6', C: '#ffffff' }),
  bigFeather: P({ A: '#f2c94c', B: '#d9803d', C: '#fff6c9' }),
  cross: P({ A: '#c9a24b', C: '#f2e28c', r: '#e04b4b' }),
  holyWater: P({ A: '#9ad0ff', C: '#ffffff', y: '#c9a24b' }),
  badge: P({ A: '#c9a24b', C: '#f2e28c', D: '#e04b4b' }),
  compass: P({ A: '#8a6a3f', C: '#e04b4b', w: '#f4f1ea' }),
  keyBox: P({ A: '#a06a2a', B: '#7a4d1e', C: '#d9a441', y: '#f2c94c' }),
  hammer: P({ A: '#8a8a9a', B: '#55556a', C: '#c9ced8', D: '#8a5a2a', r: '#e04b4b' }),
  nugget: P({ A: '#e0b23c', B: '#a57a1a', C: '#fff0a6' }),
  ironSword: P({ A: '#b8bcc8', C: '#ffffff', D: '#7a5a3a' }),
  knightSword: P({ A: '#7ad3ff', C: '#ffffff', D: '#c9a24b' }),
  holySword: P({ A: '#f2c94c', C: '#ffffff', D: '#e04b4b' }),
  ironShield: P({ A: '#7a5a3a', B: '#b8bcc8', C: '#e6e6ee', D: '#5a5a6a' }),
  knightShield: P({ A: '#c9a24b', B: '#3f6fd6', C: '#9ac0ff', D: '#ffffff' }),
  holyShield: P({ A: '#f2c94c', B: '#e04b4b', C: '#ff9a8c', D: '#ffffff' }),
  fireStaff: P({ A: '#e04b4b', C: '#ff9a8c', D: '#8a5a2a' }),
  heartStaff: P({ A: '#4fbf4a', C: '#a6eb8a', D: '#8a5a2a' }),
  iceStaff: P({ A: '#3f8fd6', C: '#9ad0ff', D: '#8a5a2a' }),
};
