#!/usr/bin/env node
// Regenerates src/data/floors.js from the map arrays that gdut-yy/MagicTower
// recovered from the original Flash game (see tools/reference/).
//
//   node tools/gen-floors.mjs
//
// The reference uses 97/98/99 as "arrival" markers inside the grid; they are
// stripped into metadata here.  A handful of cells are remapped so the
// hidden-floor bosses and the 19F/21F boss variants get their own ids.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(here, 'reference/gdut-magictower-README.md'), 'utf8');

const grids = {};
for (const m of src.matchAll(/mt_line_(\d+)\[(\d+)\] = new Array\(([^)]*)\)/g)) {
  const floor = Number(m[1]);
  const row = Number(m[2]);
  grids[floor] ??= [];
  grids[floor][row] = m[3].split(',').map((v) => Number(v.trim()));
}

const FLOOR_COUNT = 27;
for (let f = 0; f < FLOOR_COUNT; f++) {
  if (!grids[f] || grids[f].length !== 11 || grids[f].some((r) => r.length !== 11)) {
    throw new Error(`floor ${f} is not 11x11`);
  }
}

// --- per-floor tweaks --------------------------------------------------------
const set = (f, x, y, v) => { grids[f][y][x] = v; };

// 19F: the two 红衣魔王 guarding the holy weapons are the stronger variant.
set(19, 2, 5, 153);
set(19, 8, 5, 153);
// 21F: the true form of the final boss, plus the (initially hidden) way up to
// the hidden floors and the arrival cell used when coming back down.
set(21, 5, 1, 159);
set(21, 5, 0, 13);
// hidden floors: phantom copies of the boss
for (const [f, x, y] of [[23, 2, 5], [24, 5, 8], [25, 8, 5], [26, 5, 7]]) set(f, x, y, 259);
// 23F(中): the locked door in the middle is really a one-way portal to the abyss.
set(24, 5, 6, 300);

// --- names -------------------------------------------------------------------
const NAMES = {
  0: ['0', '塔外 · 序章'],
  22: ['22', '隐藏层 22 · 封印之厅'],
  23: ['23L', '隐藏层 23 · 炎之殿'],
  24: ['23', '隐藏层 23 · 深渊入口'],
  25: ['23R', '隐藏层 23 · 心之殿'],
  26: ['24', '最底层 · 血影封印'],
};
for (let f = 1; f <= 21; f++) NAMES[f] = [String(f), `主塔 ${f} 层`];

// --- stair routing -----------------------------------------------------------
// default: up-stairs -> f+1 (arrive at its "up" marker), down -> f-1 ("down" marker)
const EXITS = {
  21: { '5,0': { floor: 22, arrive: 'up' }, '5,7': { floor: 20, arrive: 'down' } },
  22: {
    '5,0': { floor: 21, arrive: 'down' },
    '0,5': { floor: 23, arrive: 'up' },
    '10,5': { floor: 25, arrive: 'up' },
    '5,10': { floor: 24, arrive: 'up' },
  },
  23: { '10,5': { floor: 22, arrive: 'down' } },
  24: { '5,0': { floor: 22, arrive: 'down' } },
  25: { '0,5': { floor: 22, arrive: 'down' } },
  26: { '5,10': { floor: 22, arrive: 'down' } },
};

const floors = [];
for (let f = 0; f < FLOOR_COUNT; f++) {
  const map = grids[f].map((r) => r.slice());
  let arriveUp = null;
  let arriveDown = null;
  let start = null;
  for (let y = 0; y < 11; y++) {
    for (let x = 0; x < 11; x++) {
      const v = map[y][x];
      if (v === 97) { arriveUp = [x, y]; map[y][x] = 0; }
      if (v === 98) { arriveDown = [x, y]; map[y][x] = 0; }
      if (v === 99) { start = [x, y]; map[y][x] = 0; }
    }
  }
  if (f === 21) arriveDown = [5, 1];
  const exits = EXITS[f] ?? {};
  if (!EXITS[f]) {
    for (let y = 0; y < 11; y++) {
      for (let x = 0; x < 11; x++) {
        if (map[y][x] === 13) exits[`${x},${y}`] = { floor: f + 1, arrive: 'up' };
        if (map[y][x] === 14) exits[`${x},${y}`] = { floor: f - 1, arrive: 'down' };
      }
    }
  }
  floors.push({ id: f, name: NAMES[f][0], title: NAMES[f][1], map, arriveUp, arriveDown, start, exits });
}

const fmtRow = (r) => '    [' + r.map((v) => String(v).padStart(3)).join(',') + '],';
let out = `// GENERATED by tools/gen-floors.mjs — do not edit by hand.
// Map data of 魔塔 v1.12 (24层, by 胖老鼠), recovered from the original Flash
// game by gdut-yy/MagicTower.  Coordinates are [x, y]; map[y][x].
// Tile ids: see src/data/tiles.js.

export const FLOOR_COUNT = ${FLOOR_COUNT};
export const START_FLOOR = 0;

export const FLOORS = [
`;
for (const fl of floors) {
  out += `  {\n    id: ${fl.id}, name: ${JSON.stringify(fl.name)}, title: ${JSON.stringify(fl.title)},\n`;
  out += `    arriveUp: ${JSON.stringify(fl.arriveUp)}, arriveDown: ${JSON.stringify(fl.arriveDown)}, start: ${JSON.stringify(fl.start)},\n`;
  out += `    exits: ${JSON.stringify(fl.exits)},\n`;
  out += `    map: [\n${fl.map.map(fmtRow).join('\n')}\n    ],\n  },\n`;
}
out += `];\n`;

writeFileSync(join(here, '../src/data/floors.js'), out);
console.log(`wrote ${floors.length} floors`);
